--[[pod_format="raw",created="2024-03-26 07:03:01",modified="2024-03-28 00:52:50",revision=326]]

function get_info()
	return {
		{ 
			sprite = --[[pod,pod_type="image"]]unpod("b64:bHo0AM4BAABuAgAA8ExweHUAQyAtPAQwDfYTDVANBvcVBg0gDQYXDxUC-xgPAg8VFwYNEAYXDv8YEw4XBgANFw4MAiw_-AwOFw0GBw5MDjIO-AwOBxYHAjxiDvwLAgcWBxIsYg4sPvwFFQBQDAIcchwkABAEGQDyBQwCHFIcDlIO-AMHFgciDAIcMixiDQBFDiKcYhcAIZxSLwBwHhK8MtweTB4AsAIOEvwGLiwOEg4sbAAQHhAAYgQOIg4cIhEAoD4i-AMyDiwSLAIOALAuAg4CDAL8AkJ8HhwAgEIMAg7sInwCDQAwTiIMGwCwCi4HFgdeIgwC-AsKABBuCgAwCAI_FQAiAg4jAGEFTgcWB44MAAICAIOsAgxeBxYHfiEACwIAECIcAEW_UgwCAgDyEEJuBxYHzgIOAg5yDFKOBxYH3gIOAi6ingcWB-4DAg4CACASvg8AEQYNABDeCwAfGQUAGUIEEv4DTwBCGgL_AgoAExkKAIICAgoUCgL_AQwANAkXCQwAUgoEFwQKDACiAQIJBxIHCQL_AA4AUwQGFQYEDgBTAgIFHgU0ADMDAh5WAB8ZBQAH8QYGDRf_FxcNAAYX-hUXBhANBhf_ExdMAqD3FQYNUA32Ew0w"), 
			artist = "LouieChapm",
			id = 10,
			lore = "Kalikan, from Kalikan"
		}
	}
end
